# Example of multiple stages in the pipeline
# The stages will run in the order they appear.
# Stage B will be treated as if it is dependent on Stage A

trigger: none

pool:
  vmImage: 'ubuntu-18.04' 

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - script: echo "A1"

  - job: A2
    steps:
    - script: echo "A2"

- stage: B
  jobs:
  - job: B1
    steps:
    - script: echo "B1"

  - job: B2
    steps:
    - script: echo "B2"