# Example of sequential jobs in the pipeline
# job J2 is dependent on J1

trigger: none

pool:
  vmImage: 'vs2017-win2016' 

stages:
- stage: MyStage
  jobs:
  - job: MyJob
    timeoutInMinutes: 1
    steps:
    - task: InlinePowershell@1
      inputs:
        Script: |
          Write-Output 'Going to sleep'

          Start-Sleep -s 180

          Write-Output 'Waking up'

          
